export const pianoKeys = [
  { midiIndex: 0, noteName: "C-1" },
  { midiIndex: 1, noteName: "C#-1" },
  { midiIndex: 2, noteName: "D-1" },
  { midiIndex: 3, noteName: "D#-1" },
  { midiIndex: 4, noteName: "E-1" },
  { midiIndex: 5, noteName: "F-1" },
  { midiIndex: 6, noteName: "F#-1" },
  { midiIndex: 7, noteName: "G-1" },
  { midiIndex: 8, noteName: "G#-1" },
  { midiIndex: 9, noteName: "A-1" },
  { midiIndex: 10, noteName: "A#-1" },
  { midiIndex: 11, noteName: "B-1" },
  { midiIndex: 12, noteName: "C0" },
  { midiIndex: 13, noteName: "C#0" },
  { midiIndex: 14, noteName: "D0" },
  { midiIndex: 15, noteName: "D#0" },
  { midiIndex: 16, noteName: "E0" },
  { midiIndex: 17, noteName: "F0" },
  { midiIndex: 18, noteName: "F#0" },
  { midiIndex: 19, noteName: "G0" },
  { midiIndex: 20, noteName: "G#0" },
  { midiIndex: 21, noteName: "A0" },
  { midiIndex: 22, noteName: "A#0" },
  { midiIndex: 23, noteName: "B0" },
  { midiIndex: 24, noteName: "C1" },
  { midiIndex: 25, noteName: "C#1" },
  { midiIndex: 26, noteName: "D1" },
  { midiIndex: 27, noteName: "D#1" },
  { midiIndex: 28, noteName: "E1" },
  { midiIndex: 29, noteName: "F1" },
  { midiIndex: 30, noteName: "F#1" },
  { midiIndex: 31, noteName: "G1" },
  { midiIndex: 32, noteName: "G#1" },
  { midiIndex: 33, noteName: "A1" },
  { midiIndex: 34, noteName: "A#1" },
  { midiIndex: 35, noteName: "B1" },
  { midiIndex: 36, noteName: "C2" },
  { midiIndex: 37, noteName: "C#2" },
  { midiIndex: 38, noteName: "D2" },
  { midiIndex: 39, noteName: "D#2" },
  { midiIndex: 40, noteName: "E2" },
  { midiIndex: 41, noteName: "F2" },
  { midiIndex: 42, noteName: "F#2" },
  { midiIndex: 43, noteName: "G2" },
  { midiIndex: 44, noteName: "G#2" },
  { midiIndex: 45, noteName: "A2" },
  { midiIndex: 46, noteName: "A#2" },
  { midiIndex: 47, noteName: "B2" },
  { midiIndex: 48, noteName: "C3" },
  { midiIndex: 49, noteName: "C#3" },
  { midiIndex: 50, noteName: "D3" },
  { midiIndex: 51, noteName: "D#3" },
  { midiIndex: 52, noteName: "E3" },
  { midiIndex: 53, noteName: "F3" },
  { midiIndex: 54, noteName: "F#3" },
  { midiIndex: 55, noteName: "G3" },
  { midiIndex: 56, noteName: "G#3" },
  { midiIndex: 57, noteName: "A3" },
  { midiIndex: 58, noteName: "A#3" },
  { midiIndex: 59, noteName: "B3" },
  { midiIndex: 60, noteName: "C4" },
  { midiIndex: 61, noteName: "C#4" },
  { midiIndex: 62, noteName: "D4" },
  { midiIndex: 63, noteName: "D#4" },
  { midiIndex: 64, noteName: "E4" },
  { midiIndex: 65, noteName: "F4" },
  { midiIndex: 66, noteName: "F#4" },
  { midiIndex: 67, noteName: "G4" },
  { midiIndex: 68, noteName: "G#4" },
  { midiIndex: 69, noteName: "A4" },
  { midiIndex: 70, noteName: "A#4" },
  { midiIndex: 71, noteName: "B4" },
  { midiIndex: 72, noteName: "C5" },
  { midiIndex: 73, noteName: "C#5" },
  { midiIndex: 74, noteName: "D5" },
  { midiIndex: 75, noteName: "D#5" },
  { midiIndex: 76, noteName: "E5" },
  { midiIndex: 77, noteName: "F5" },
  { midiIndex: 78, noteName: "F#5" },
  { midiIndex: 79, noteName: "G5" },
  { midiIndex: 80, noteName: "G#5" },
  { midiIndex: 81, noteName: "A5" },
  { midiIndex: 82, noteName: "A#5" },
  { midiIndex: 83, noteName: "B5" },
  { midiIndex: 84, noteName: "C6" },
  { midiIndex: 85, noteName: "C#6" },
  { midiIndex: 86, noteName: "D6" },
  { midiIndex: 87, noteName: "D#6" },
  { midiIndex: 88, noteName: "E6" },
  { midiIndex: 89, noteName: "F6" },
  { midiIndex: 90, noteName: "F#6" },
  { midiIndex: 91, noteName: "G6" },
  { midiIndex: 92, noteName: "G#6" },
  { midiIndex: 93, noteName: "A6" },
  { midiIndex: 94, noteName: "A#6" },
  { midiIndex: 95, noteName: "B6" },
  { midiIndex: 96, noteName: "C7" },
  { midiIndex: 97, noteName: "C#7" },
  { midiIndex: 98, noteName: "D7" },
  { midiIndex: 99, noteName: "D#7" },
  { midiIndex: 100, noteName: "E7" },
  { midiIndex: 101, noteName: "F7" },
  { midiIndex: 102, noteName: "F#7" },
  { midiIndex: 103, noteName: "G7" },
  { midiIndex: 104, noteName: "G#7" },
  { midiIndex: 105, noteName: "A7" },
  { midiIndex: 106, noteName: "A#7" },
  { midiIndex: 107, noteName: "B7" },
];

export const keyNames = [
  "q",
  "2",
  "w",
  "3",
  "e",
  "r",
  "5",
  "t",
  "6",
  "y",
  "7",
  "u",
  "z",
  "s",
  "x",
  "d",
  "c",
  "v",
  "g",
  "b",
  "h",
  "n",
  "j",
  "m",
  ",",
  "l",
  ".",
  ";",
  "/",
];
